[base]
name = neurots
files = {[base]name} tests docs/source/conf.py examples

[tox]
envlist =
    check-packaging
    lint
    docs
    min_versions
    py{310,311,312}

minversion = 3.18

[testenv]
extras =
    test
commands =
    python -m pytest \
        -n {env:PYTEST_NPROCS:4} \
        --basetemp={envtmpdir} \
        --cov={[base]name} \
        --html reports/pytest-{envname}.html \
        --junit-xml=reports/pytest-{envname}.xml \
        --self-contained-html \
        {posargs}
    python -m coverage xml
    python -m coverage html
    python -m coverage report

[testenv:check-packaging]
skip_install = true
deps =
    build
    twine
commands =
    python -m build -o {envtmpdir}/dist
    twine check {envtmpdir}/dist/*

[testenv:min_versions]
skip_install = true
extras =
basepython = python3.10
deps =
    pip
    uv
commands =
    uv pip install --python {envpython} --dry-run --resolution=lowest-direct -e '.[test]'

[testenv:lint]
basepython = python3.12
deps = ruff
commands =
    ruff check {[base]files}
    ruff format --check {[base]files}

[testenv:format]
basepython = python3
skip_install = true
deps =
    codespell
    ruff
commands =
    codespell -i 3 -x .codespellignorelines -w {[base]files} README.md CHANGELOG.md docs/source
    ruff check --fix {[base]files}
    ruff format {[base]files}

[testenv:docs]
changedir = docs
extras = docs
allowlist_externals =
    make
# set warnings as errors using the -W sphinx option
commands =
    make clean
    make html SPHINXOPTS=-W
